name: Powershell script
on:
  push:
    branches:
      - master

jobs:
  myJob:
    name: PS - Update list
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Run PowerShell script
        shell: pwsh
        run: | 
          ./write_message.ps1
